# NTUTrainRL2_5
This is the lecture notes for NTU Train Course of R Project Lecture 2_5

## Plotly

RStudio使用者需要下載最新版本的[RStudio](https://www.rstudio.com/products/rstudio/download/)。

```{r}
install.packages("plotly")
library(plotly)
```

### 第一個Plotly圖

```{r}
setwd("C:/NTUTrainRL2")
employment <- read.table("data/employmentTW.csv", sep=",", header=T)
employment <- transform(
  employment,
  unemploymentRate = (workingPopInThousand-employedPopInThousand)/workingPopInThousand
)
firstPlotly <- plot_ly(employment, x = year, y = unemploymentRate)
firstPlotly
```

### 練習使用`type=`與`mode=`

在`mode=`中可以用`+`號結合`lines`、`markers`與`text`。

```{r}
secondPlotly <- plot_ly(employment, x = year, y = unemploymentRate, type = "scatter", mode = "markers")
secondPlotly
```

### 加上LOESS平滑線

使用`add_trace()`函數。

```{r}
smoothLine <- loess(unemploymentRate ~ year, data = employment)
thirdPlotly <- plot_ly(employment, x=year, y=unemploymentRate, name="raw data", mode="markers+lines") %>%
  add_trace(y=fitted(smoothLine), name="loess", mode="lines")
thirdPlotly
```

### 隱藏圖例

使用`layout()`函數。

```{r}
fourthPlotly <- thirdPlotly %>%
  layout(showlegend = FALSE)
fourthPlotly
```

### 不一定要data frame

```{r}
class(volcano)
fifthPlotly <- plot_ly(z = volcano, type = "surface")
fifthPlotly

sixthPlotly <- plot_ly(z = volcano, type = "contour")
sixthPlotly
```

### 顏色參數

```{r}
#先整理一下資料集
fiveCities <- read.table("data/fiveCities.csv", sep=",", header=T)
popIncreaseMelted <- melt(fiveCities[,1:6], id.vars="year", variable.name = "city", value.name="popIncrease")
unemployMelted <- melt(fiveCities[, c(1, 7:11)], id.vars="year", variable.name = "city", value.name="unemploy")
city <- gsub("_popIncrease", "", popIncreaseMelted$city)
fiveCitiesMelted <- data.frame(city, popIncreaseMelted[,c(1,3)], unemployMelted$unemploy)
colnames(fiveCitiesMelted) <- c("city", "year", "popIncreaseRate", "unemploymentRate")
```

使用`color=`可以依類別著色。

```{r}
seventhPlotly <- plot_ly(fiveCitiesMelted, x = popIncreaseRate, y = unemploymentRate, color = city, mode = "markers")
seventhPlotly
```

也可以依數值著色。

```{r}
eighthPlotly <- plot_ly(fiveCitiesMelted, x = popIncreaseRate, y = unemploymentRate, color = unemploymentRate, mode = "markers")
eighthPlotly
```

以及用`colors=`指定調色盤，調色盤的名稱可以參考[這個連結](http://isu.r-forge.r-project.org/vistat/2013-04-08-plotting-symbols-and-color-palettes/brewer-pal.png)。

```{r}
ninthPlotly <- plot_ly(fiveCitiesMelted, x = popIncreaseRate, y = unemploymentRate, color = unemploymentRate, colors="Greens", mode = "markers")
ninthPlotly
```

### 



## Reference
* [Plotly R Library 2.0](https://plot.ly/r/)

&copy; Tony Yao-Jen Kuo 2016