# NTUTrainRL2_1
This is the lecture notes for NTU Train Course of R Project Lecture 2_1

## R Basic Plotting System

### 資料載入

```{r}
setwd("C:/NTUTrainRL2")
Sys.setlocale(category = "LC_ALL", locale = "cht")
accidentList <- readRDS('data/accidentList.rds')
colnames(accidentList) <- c("縣市別", "醫院別", "性別", "國籍別", "年齡", "醫療檢傷", "救護檢傷")
summary(accidentList)
accidentList <- accidentList[accidentList$年齡!=101,]
```

### 長條圖bar plot

以圖形高度代表資料量的統計圖形，主要用來處理離散型資料。

```{r}
par(mfrow=c(3,2))
barPlots <- function(){
  #titles <- c("依縣市別", "依性別", "依國籍", "依醫療檢傷", "依救護檢傷")
  variables <- names(accidentList[, c(-2, -5)])
  for (name in variables){
    barplot(table(accidentList[ ,name]), main=paste("依",name), ylab="人數")
  }
}
barPlots()
barplot(table(accidentList$醫院別), main="依醫院別", ylab="人數", las=2)
```

### 直方圖histogram

觀察連續型資料的分布。

```{r}
par(mfrow=c(1,1))
hist(na.omit(accidentList$年齡), xlab="年齡", ylab="密度",  main="依年齡", breaks=15, freq=FALSE, ylim=c(0, 0.12), col="skyblue")
rug(jitter(accidentList$年齡))#在X軸上顯示資料密度
lines(density(accidentList$年齡, na.rm=TRUE), col="red", lwd=2)#hist的freq要設為false才看得到
```

### 盒鬚圖boxplot

```{r}
boxplot(年齡 ~ 縣市別, data = accidentList, main='年齡依縣市別')
boxplot(年齡 ~ 性別, data = accidentList, main='年齡依性別')
boxplot(年齡 ~ 國籍別, data = accidentList, main='年齡依國籍別')
boxplot(年齡 ~ 醫療檢傷, data = accidentList, main='年齡依醫療檢傷')
boxplot(年齡 ~ 救護檢傷, data = accidentList, main='年齡依救護檢傷')
```

## Reference
* R in Action, Robert I. Kabacoff
* R Graphics Cookbook

&copy; Tony Yao-Jen Kuo 2015
